<?php

namespace App\Http\Controllers\Auth;

use App\Models\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules\Password;

class RegisterController extends Controller
{
    protected $redirectTo = '/customer';

    public function showRegistrationForm()
    {
        return view('auth.register');
    }

    public function register(Request $request)
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
            'password' => ['required', 'string', Password::min(8), 'confirmed'],
        ]);

        // Create the user together with their customer profile and their
        // customer account in a single transaction so a partial registration
        // (e.g. user without a customer record) can never occur.
        $user = DB::transaction(function () use ($validated) {
            $user = User::create([
                'name' => $validated['name'],
                'email' => $validated['email'],
                'password' => Hash::make($validated['password']),
                'is_superadmin' => false,
            ]);

            // Assign the customer role
            $user->assignRole('customer');

            // Create the customer profile linked to the user (address and
            // contact details are completed later from the customer panel)
            $customer = $user->customers()->create([
                'status' => 'active',
            ]);

            // Create the customer account with a zero starting balance
            // (account_number is auto-generated by the CustomerAccount model)
            $customer->account()->create([
                'total_credit' => 0,
                'total_debit' => 0,
                'balance' => 0,
            ]);

            return $user;
        });

        // Send the e-mail verification link (the login flow gates customers
        // behind verified e-mail addresses).
        $user->sendEmailVerificationNotification();

        Auth::login($user);

        return redirect($this->redirectTo);
    }
}
